-- MySQL Script generated by MySQL Workbench
-- Tue Jun  2 19:27:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbpagins
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbpagins
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `dbpagins`.`moderador`
-- -----------------------------------------------------
CREATE TABLE `moderador` (
  `id_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(25) NOT NULL,
  `apellidos` VARCHAR(25) NOT NULL,
  `user` VARCHAR(20) NOT NULL,
  `pass` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpagins`.`category`
-- -----------------------------------------------------
CREATE TABLE `category` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `name_cat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpagins`.`post`
-- -----------------------------------------------------
CREATE TABLE `post` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `tittle_post` VARCHAR(255) NOT NULL,
  `archivo` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `date_post` DATETIME NOT NULL,
  `status` BINARY(2) NOT NULL,
  `category_id_category` INT NOT NULL,
  `usuarios_id_usuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_post`),
  UNIQUE INDEX `id_post_UNIQUE` (`id_post` ASC),
  INDEX `fk_post_category_idx` (`category_id_category` ASC),
  INDEX `fk_post_usuarios1_idx` (`usuarios_id_usuario` ASC),
  CONSTRAINT `fk_post_category`
    FOREIGN KEY (`category_id_category`)
    REFERENCES `category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `moderador` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpagins`.`admin`
-- -----------------------------------------------------
CREATE TABLE `admin` (
  `id_admin` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(30) NOT NULL,
  `user` VARCHAR(30) NOT NULL,
  `pass` VARCHAR(16) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_admin`),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC),
  UNIQUE INDEX `mail_UNIQUE` (`email` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  UNIQUE INDEX `apellido_UNIQUE` (`apellido` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpagins`.`contacto`
-- -----------------------------------------------------
CREATE TABLE `contacto` (
  `idcontacto` INT NOT NULL,
  `asunto` VARCHAR(45) NOT NULL,
  `contenido` TEXT(1000) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idcontacto`),
  UNIQUE INDEX `idcontacto_UNIQUE` (`idcontacto` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
